// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: health_check.proto

#include "health_check.pb.h"
#include "health_check.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace sfcas {
namespace healthcheck {

static const char* HealthCheck_method_names[] = {
  "/sfcas.healthcheck.HealthCheck/Check",
  "/sfcas.healthcheck.HealthCheck/Watch",
};

std::unique_ptr< HealthCheck::Stub> HealthCheck::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HealthCheck::Stub> stub(new HealthCheck::Stub(channel, options));
  return stub;
}

HealthCheck::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Check_(HealthCheck_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Watch_(HealthCheck_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status HealthCheck::Stub::Check(::grpc::ClientContext* context, const ::sfcas::healthcheck::HealthCheckRequest& request, ::sfcas::healthcheck::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sfcas::healthcheck::HealthCheckRequest, ::sfcas::healthcheck::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Check_, context, request, response);
}

void HealthCheck::Stub::async::Check(::grpc::ClientContext* context, const ::sfcas::healthcheck::HealthCheckRequest* request, ::sfcas::healthcheck::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sfcas::healthcheck::HealthCheckRequest, ::sfcas::healthcheck::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, std::move(f));
}

void HealthCheck::Stub::async::Check(::grpc::ClientContext* context, const ::sfcas::healthcheck::HealthCheckRequest* request, ::sfcas::healthcheck::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sfcas::healthcheck::HealthCheckResponse>* HealthCheck::Stub::PrepareAsyncCheckRaw(::grpc::ClientContext* context, const ::sfcas::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sfcas::healthcheck::HealthCheckResponse, ::sfcas::healthcheck::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Check_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sfcas::healthcheck::HealthCheckResponse>* HealthCheck::Stub::AsyncCheckRaw(::grpc::ClientContext* context, const ::sfcas::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::sfcas::healthcheck::HealthCheckResponse>* HealthCheck::Stub::WatchRaw(::grpc::ClientContext* context, const ::sfcas::healthcheck::HealthCheckRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::sfcas::healthcheck::HealthCheckResponse>::Create(channel_.get(), rpcmethod_Watch_, context, request);
}

void HealthCheck::Stub::async::Watch(::grpc::ClientContext* context, const ::sfcas::healthcheck::HealthCheckRequest* request, ::grpc::ClientReadReactor< ::sfcas::healthcheck::HealthCheckResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::sfcas::healthcheck::HealthCheckResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Watch_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::sfcas::healthcheck::HealthCheckResponse>* HealthCheck::Stub::AsyncWatchRaw(::grpc::ClientContext* context, const ::sfcas::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::sfcas::healthcheck::HealthCheckResponse>::Create(channel_.get(), cq, rpcmethod_Watch_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::sfcas::healthcheck::HealthCheckResponse>* HealthCheck::Stub::PrepareAsyncWatchRaw(::grpc::ClientContext* context, const ::sfcas::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::sfcas::healthcheck::HealthCheckResponse>::Create(channel_.get(), cq, rpcmethod_Watch_, context, request, false, nullptr);
}

HealthCheck::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HealthCheck_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HealthCheck::Service, ::sfcas::healthcheck::HealthCheckRequest, ::sfcas::healthcheck::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HealthCheck::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sfcas::healthcheck::HealthCheckRequest* req,
             ::sfcas::healthcheck::HealthCheckResponse* resp) {
               return service->Check(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HealthCheck_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< HealthCheck::Service, ::sfcas::healthcheck::HealthCheckRequest, ::sfcas::healthcheck::HealthCheckResponse>(
          [](HealthCheck::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sfcas::healthcheck::HealthCheckRequest* req,
             ::grpc::ServerWriter<::sfcas::healthcheck::HealthCheckResponse>* writer) {
               return service->Watch(ctx, req, writer);
             }, this)));
}

HealthCheck::Service::~Service() {
}

::grpc::Status HealthCheck::Service::Check(::grpc::ServerContext* context, const ::sfcas::healthcheck::HealthCheckRequest* request, ::sfcas::healthcheck::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HealthCheck::Service::Watch(::grpc::ServerContext* context, const ::sfcas::healthcheck::HealthCheckRequest* request, ::grpc::ServerWriter< ::sfcas::healthcheck::HealthCheckResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sfcas
}  // namespace healthcheck

