// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sfcas.proto

#include "sfcas.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace sfcas_dfs {

inline constexpr LocationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LocationRequest::LocationRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LocationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LocationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LocationRequestDefaultTypeInternal() {}
  union {
    LocationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LocationRequestDefaultTypeInternal _LocationRequest_default_instance_;

inline constexpr LocationReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LocationReply::LocationReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LocationReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LocationReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LocationReplyDefaultTypeInternal() {}
  union {
    LocationReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LocationReplyDefaultTypeInternal _LocationReply_default_instance_;

inline constexpr DataRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        offset_{::uint64_t{0u}},
        size_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DataRequest::DataRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DataRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataRequestDefaultTypeInternal() {}
  union {
    DataRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataRequestDefaultTypeInternal _DataRequest_default_instance_;

inline constexpr DataReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : chunk_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DataReply::DataReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DataReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataReplyDefaultTypeInternal() {}
  union {
    DataReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataReplyDefaultTypeInternal _DataReply_default_instance_;
}  // namespace sfcas_dfs
static ::_pb::Metadata file_level_metadata_sfcas_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_sfcas_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_sfcas_2eproto = nullptr;
const ::uint32_t TableStruct_sfcas_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::LocationRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::LocationRequest, _impl_.filename_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::LocationReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::LocationReply, _impl_.ip_),
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::LocationReply, _impl_.port_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::DataRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::DataRequest, _impl_.filename_),
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::DataRequest, _impl_.offset_),
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::DataRequest, _impl_.size_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::DataReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::sfcas_dfs::DataReply, _impl_.chunk_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::sfcas_dfs::LocationRequest)},
        {9, -1, -1, sizeof(::sfcas_dfs::LocationReply)},
        {19, -1, -1, sizeof(::sfcas_dfs::DataRequest)},
        {30, -1, -1, sizeof(::sfcas_dfs::DataReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::sfcas_dfs::_LocationRequest_default_instance_._instance,
    &::sfcas_dfs::_LocationReply_default_instance_._instance,
    &::sfcas_dfs::_DataRequest_default_instance_._instance,
    &::sfcas_dfs::_DataReply_default_instance_._instance,
};
const char descriptor_table_protodef_sfcas_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013sfcas.proto\022\tsfcas_dfs\"#\n\017LocationRequ"
    "est\022\020\n\010filename\030\001 \001(\t\")\n\rLocationReply\022\n"
    "\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\t\"=\n\013DataRequest\022"
    "\020\n\010filename\030\001 \001(\t\022\016\n\006offset\030\002 \001(\004\022\014\n\004siz"
    "e\030\003 \001(\004\"\032\n\tDataReply\022\r\n\005chunk\030\001 \001(\0142\227\001\n\n"
    "FileAccess\022K\n\021get_file_location\022\032.sfcas_"
    "dfs.LocationRequest\032\030.sfcas_dfs.Location"
    "Reply\"\000\022<\n\010get_data\022\026.sfcas_dfs.DataRequ"
    "est\032\024.sfcas_dfs.DataReply\"\0000\001b\006proto3"
};
static ::absl::once_flag descriptor_table_sfcas_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sfcas_2eproto = {
    false,
    false,
    357,
    descriptor_table_protodef_sfcas_2eproto,
    "sfcas.proto",
    &descriptor_table_sfcas_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_sfcas_2eproto::offsets,
    file_level_metadata_sfcas_2eproto,
    file_level_enum_descriptors_sfcas_2eproto,
    file_level_service_descriptors_sfcas_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sfcas_2eproto_getter() {
  return &descriptor_table_sfcas_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sfcas_2eproto(&descriptor_table_sfcas_2eproto);
namespace sfcas_dfs {
// ===================================================================

class LocationRequest::_Internal {
 public:
};

LocationRequest::LocationRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sfcas_dfs.LocationRequest)
}
inline PROTOBUF_NDEBUG_INLINE LocationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : filename_(arena, from.filename_),
        _cached_size_{0} {}

LocationRequest::LocationRequest(
    ::google::protobuf::Arena* arena,
    const LocationRequest& from)
    : ::google::protobuf::Message(arena) {
  LocationRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:sfcas_dfs.LocationRequest)
}
inline PROTOBUF_NDEBUG_INLINE LocationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        _cached_size_{0} {}

inline void LocationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LocationRequest::~LocationRequest() {
  // @@protoc_insertion_point(destructor:sfcas_dfs.LocationRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LocationRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LocationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sfcas_dfs.LocationRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LocationRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 42, 2> LocationRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LocationRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LocationRequest, _impl_.filename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(LocationRequest, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\10\0\0\0\0\0\0"
    "sfcas_dfs.LocationRequest"
    "filename"
  }},
};

::uint8_t* LocationRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sfcas_dfs.LocationRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sfcas_dfs.LocationRequest.filename");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sfcas_dfs.LocationRequest)
  return target;
}

::size_t LocationRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sfcas_dfs.LocationRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LocationRequest::_class_data_ = {
    LocationRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LocationRequest::GetClassData() const {
  return &_class_data_;
}

void LocationRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LocationRequest*>(&to_msg);
  auto& from = static_cast<const LocationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sfcas_dfs.LocationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LocationRequest::CopyFrom(const LocationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sfcas_dfs.LocationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LocationRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LocationRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LocationRequest::InternalSwap(LocationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
}

::google::protobuf::Metadata LocationRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfcas_2eproto_getter, &descriptor_table_sfcas_2eproto_once,
      file_level_metadata_sfcas_2eproto[0]);
}
// ===================================================================

class LocationReply::_Internal {
 public:
};

LocationReply::LocationReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sfcas_dfs.LocationReply)
}
inline PROTOBUF_NDEBUG_INLINE LocationReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : ip_(arena, from.ip_),
        port_(arena, from.port_),
        _cached_size_{0} {}

LocationReply::LocationReply(
    ::google::protobuf::Arena* arena,
    const LocationReply& from)
    : ::google::protobuf::Message(arena) {
  LocationReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:sfcas_dfs.LocationReply)
}
inline PROTOBUF_NDEBUG_INLINE LocationReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : ip_(arena),
        port_(arena),
        _cached_size_{0} {}

inline void LocationReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LocationReply::~LocationReply() {
  // @@protoc_insertion_point(destructor:sfcas_dfs.LocationReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LocationReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.ip_.Destroy();
  _impl_.port_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LocationReply::Clear() {
// @@protoc_insertion_point(message_clear_start:sfcas_dfs.LocationReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_.ClearToEmpty();
  _impl_.port_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LocationReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2> LocationReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LocationReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string port = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(LocationReply, _impl_.port_)}},
    // string ip = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LocationReply, _impl_.ip_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string ip = 1;
    {PROTOBUF_FIELD_OFFSET(LocationReply, _impl_.ip_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string port = 2;
    {PROTOBUF_FIELD_OFFSET(LocationReply, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\2\4\0\0\0\0\0"
    "sfcas_dfs.LocationReply"
    "ip"
    "port"
  }},
};

::uint8_t* LocationReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sfcas_dfs.LocationReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string ip = 1;
  if (!this->_internal_ip().empty()) {
    const std::string& _s = this->_internal_ip();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sfcas_dfs.LocationReply.ip");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string port = 2;
  if (!this->_internal_port().empty()) {
    const std::string& _s = this->_internal_port();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sfcas_dfs.LocationReply.port");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sfcas_dfs.LocationReply)
  return target;
}

::size_t LocationReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sfcas_dfs.LocationReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ip = 1;
  if (!this->_internal_ip().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_ip());
  }

  // string port = 2;
  if (!this->_internal_port().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LocationReply::_class_data_ = {
    LocationReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LocationReply::GetClassData() const {
  return &_class_data_;
}

void LocationReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LocationReply*>(&to_msg);
  auto& from = static_cast<const LocationReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sfcas_dfs.LocationReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (!from._internal_port().empty()) {
    _this->_internal_set_port(from._internal_port());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LocationReply::CopyFrom(const LocationReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sfcas_dfs.LocationReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LocationReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LocationReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LocationReply::InternalSwap(LocationReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_, &other->_impl_.ip_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.port_, &other->_impl_.port_, arena);
}

::google::protobuf::Metadata LocationReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfcas_2eproto_getter, &descriptor_table_sfcas_2eproto_once,
      file_level_metadata_sfcas_2eproto[1]);
}
// ===================================================================

class DataRequest::_Internal {
 public:
};

DataRequest::DataRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sfcas_dfs.DataRequest)
}
inline PROTOBUF_NDEBUG_INLINE DataRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : filename_(arena, from.filename_),
        _cached_size_{0} {}

DataRequest::DataRequest(
    ::google::protobuf::Arena* arena,
    const DataRequest& from)
    : ::google::protobuf::Message(arena) {
  DataRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, offset_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, offset_),
           offsetof(Impl_, size_) -
               offsetof(Impl_, offset_) +
               sizeof(Impl_::size_));

  // @@protoc_insertion_point(copy_constructor:sfcas_dfs.DataRequest)
}
inline PROTOBUF_NDEBUG_INLINE DataRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        _cached_size_{0} {}

inline void DataRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, offset_),
           0,
           offsetof(Impl_, size_) -
               offsetof(Impl_, offset_) +
               sizeof(Impl_::size_));
}
DataRequest::~DataRequest() {
  // @@protoc_insertion_point(destructor:sfcas_dfs.DataRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DataRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void DataRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sfcas_dfs.DataRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  ::memset(&_impl_.offset_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.size_) -
      reinterpret_cast<char*>(&_impl_.offset_)) + sizeof(_impl_.size_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DataRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 38, 2> DataRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DataRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DataRequest, _impl_.filename_)}},
    // uint64 offset = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DataRequest, _impl_.offset_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DataRequest, _impl_.offset_)}},
    // uint64 size = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DataRequest, _impl_.size_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(DataRequest, _impl_.size_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(DataRequest, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 offset = 2;
    {PROTOBUF_FIELD_OFFSET(DataRequest, _impl_.offset_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 size = 3;
    {PROTOBUF_FIELD_OFFSET(DataRequest, _impl_.size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
    "\25\10\0\0\0\0\0\0"
    "sfcas_dfs.DataRequest"
    "filename"
  }},
};

::uint8_t* DataRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sfcas_dfs.DataRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sfcas_dfs.DataRequest.filename");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // uint64 offset = 2;
  if (this->_internal_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_offset(), target);
  }

  // uint64 size = 3;
  if (this->_internal_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_size(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sfcas_dfs.DataRequest)
  return target;
}

::size_t DataRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sfcas_dfs.DataRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  // uint64 offset = 2;
  if (this->_internal_offset() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_offset());
  }

  // uint64 size = 3;
  if (this->_internal_size() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DataRequest::_class_data_ = {
    DataRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DataRequest::GetClassData() const {
  return &_class_data_;
}

void DataRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DataRequest*>(&to_msg);
  auto& from = static_cast<const DataRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sfcas_dfs.DataRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (from._internal_offset() != 0) {
    _this->_internal_set_offset(from._internal_offset());
  }
  if (from._internal_size() != 0) {
    _this->_internal_set_size(from._internal_size());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DataRequest::CopyFrom(const DataRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sfcas_dfs.DataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DataRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DataRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DataRequest::InternalSwap(DataRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DataRequest, _impl_.size_)
      + sizeof(DataRequest::_impl_.size_)
      - PROTOBUF_FIELD_OFFSET(DataRequest, _impl_.offset_)>(
          reinterpret_cast<char*>(&_impl_.offset_),
          reinterpret_cast<char*>(&other->_impl_.offset_));
}

::google::protobuf::Metadata DataRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfcas_2eproto_getter, &descriptor_table_sfcas_2eproto_once,
      file_level_metadata_sfcas_2eproto[2]);
}
// ===================================================================

class DataReply::_Internal {
 public:
};

DataReply::DataReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sfcas_dfs.DataReply)
}
inline PROTOBUF_NDEBUG_INLINE DataReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : chunk_(arena, from.chunk_),
        _cached_size_{0} {}

DataReply::DataReply(
    ::google::protobuf::Arena* arena,
    const DataReply& from)
    : ::google::protobuf::Message(arena) {
  DataReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:sfcas_dfs.DataReply)
}
inline PROTOBUF_NDEBUG_INLINE DataReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : chunk_(arena),
        _cached_size_{0} {}

inline void DataReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DataReply::~DataReply() {
  // @@protoc_insertion_point(destructor:sfcas_dfs.DataReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DataReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.chunk_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void DataReply::Clear() {
// @@protoc_insertion_point(message_clear_start:sfcas_dfs.DataReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chunk_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DataReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> DataReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DataReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes chunk = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DataReply, _impl_.chunk_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes chunk = 1;
    {PROTOBUF_FIELD_OFFSET(DataReply, _impl_.chunk_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* DataReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sfcas_dfs.DataReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes chunk = 1;
  if (!this->_internal_chunk().empty()) {
    const std::string& _s = this->_internal_chunk();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sfcas_dfs.DataReply)
  return target;
}

::size_t DataReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sfcas_dfs.DataReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes chunk = 1;
  if (!this->_internal_chunk().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_chunk());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DataReply::_class_data_ = {
    DataReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DataReply::GetClassData() const {
  return &_class_data_;
}

void DataReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DataReply*>(&to_msg);
  auto& from = static_cast<const DataReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sfcas_dfs.DataReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_chunk().empty()) {
    _this->_internal_set_chunk(from._internal_chunk());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DataReply::CopyFrom(const DataReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sfcas_dfs.DataReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DataReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DataReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DataReply::InternalSwap(DataReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.chunk_, &other->_impl_.chunk_, arena);
}

::google::protobuf::Metadata DataReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfcas_2eproto_getter, &descriptor_table_sfcas_2eproto_once,
      file_level_metadata_sfcas_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace sfcas_dfs
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
